Bring in line with other plugins. Data on host, built in dokku command to set ENV vars.

diff --git a/commands b/commands
--- a/commands
+++ b/commands
@@ -1,92 +1,106 @@
 #!/bin/bash
 #set -e;
 
-# Check if name is specified
-if [[ $1 == postgresql:* ]]; then
-    if [[ -z $2 ]]; then
-        echo "You must specify an app name"
-        exit 1
-    else
-        APP="$2"
-        # Check if app exists with the same name
-        if [[ -d "/home/git/$APP" ]]; then
-            app_exists=true
-        else
-            app_exists=false
-        fi
-    fi
-fi
+APP=$2
+
+OLDHOME=$HOME
+HOME="$DOKKU_ROOT/.postgresql"
 
 check_exists() {
-  if [[ $app_exists == false ]]; then
+  if [[ ! -d "$DOKKU_ROOT/$APP" ]]; then
     echo "App must exist before creating postgresql storage for it"
     exit 1
   fi
 }
 
-set_dokku_env() {
-  env_path=$1
-  env_var=$2
-  env_val=$3
-  ex -s -c "g/export ${env_var}=/d" -c "x" "$env_path"
-  echo "export ${env_var}=\"${env_val}\"" >> "$env_path"
+check_app() {
+  if [[ -z "$APP" ]]; then
+    echo "You must specify an app name"
+    exit 1
+  fi
 }
 
-clear_dokku_env() {
-  local ref=$1[@]
-  for x in ${!ref}; do
-    ex -s -c "g/${env_var}/d" -c "x" "$app_path/ENV"
-  done
+check_container() {
+  if [[ -z "$id" ]]; then
+    echo "Postgresql container not started cannot continue. Start with dokku postgresql:start"
+    exit 1
+  fi
 }
 
-app_path=/home/git/$APP
-
-admin_pass=$(cat /home/git/.postgresql/admin_pw)
+admin_pass=$(cat "$DOKKU_ROOT/.postgresql/admin_pw")
 postgresql_database="${APP}_production"
 
 db_image=jeffutter/postgresql
+
 id=$(docker ps | grep "$db_image":latest |  awk '{print $1}')
-postgresql_port=$(docker port "$id" 5432)
-postgresql_ip=$(docker inspect "$id" | grep IPAddress | awk '{ print $2 }' | tr -d ',"')
+postgresql_public_ip=$(docker port ${id} 5432 | awk '{split($0,a,":"); print a[1]}')
+postgresql_private_ip=$(docker inspect ${id} | grep IPAddress | awk '{ print $2 }' | tr -d ',"')
+postgresql_port=$(docker port ${id} 5432 | awk '{split($0,a,":"); print a[2]}')
+if [[ $postgresql_public_ip = "0.0.0.0" ]]; then
+  postgresql_public_ip=localhost
+fi
 
 case "$1" in
   postgresql:create)
+    check_container
+    check_app
     check_exists
 
     postgresql_password=$(openssl rand -base64 32|base64)
-    echo $postgresql_password > /home/git/.postgresql/pass_$APP
+    echo $postgresql_password > "$DOKKU_ROOT/.postgresql/pass_$APP"
 
-    admin_pw=$(cat /home/git/.postgresql/admin_pw)
-    PGPASSWORD="$admin_pw" PGUSER=root psql -h localhost -p "$postgresql_port" -w template1 <<< "CREATE USER ${APP} WITH PASSWORD '${postgresql_password}';"
-    PGPASSWORD="$admin_pw" PGUSER=root psql -h localhost -p "$postgresql_port" -w template1 <<< "CREATE DATABASE ${postgresql_database};"
-    PGPASSWORD="$admin_pw" PGUSER=root psql -h localhost -p "$postgresql_port" -w template1 <<< "GRANT ALL PRIVILEGES ON DATABASE ${postgresql_database} to ${APP};"
+    admin_pw=$(cat "$DOKKU_ROOT/.postgresql/admin_pw")
+    PGPASSWORD="$admin_pw" PGUSER=root psql -h "$postgresql_public_ip" -p "$postgresql_port" -w template1 <<< "CREATE USER ${APP} WITH PASSWORD '${postgresql_password}';"
+    PGPASSWORD="$admin_pw" PGUSER=root psql -h "$postgresql_public_ip" -p "$postgresql_port" -w template1 <<< "CREATE DATABASE ${postgresql_database};"
+    PGPASSWORD="$admin_pw" PGUSER=root psql -h "$postgresql_public_ip" -p "$postgresql_port" -w template1 <<< "GRANT ALL PRIVILEGES ON DATABASE ${postgresql_database} to ${APP};"
 
     postgresql_port=5432
-    if [[ ! -f /home/git/$APP/ENV ]]; then
-      touch /home/git/$APP/ENV
-    fi
-    set_dokku_env $app_path/ENV DATABASE_URL "postgres://${APP}:${postgresql_password}@${postgresql_ip}:${postgresql_port}/${postgresql_database}"
-    chown git: $app_path/ENV
+    dokku config:set "$APP" DATABASE_URL="postgres://${APP}:${postgresql_password}@${postgresql_private_ip}:${postgresql_port}/${postgresql_database}"
     ;;
   postgresql:delete)
+    check_container
+    check_app
     check_exists
 
-    admin_pw=$(cat /home/git/.postgresql/admin_pw)
-    PGPASSWORD="$admin_pw" PGUSER=root psql -h localhost -p "$postgresql_port" -w template1 <<< "DROP DATABASE ${postgresql_database};"
-    PGPASSWORD="$admin_pw" PGUSER=root psql -h localhost -p "$postgresql_port" -w template1 <<< "DROP USER ${APP};"
+    admin_pw=$(cat "$DOKKU_ROOT/.postgresql/admin_pw")
+    PGPASSWORD="$admin_pw" PGUSER=root psql -h "$postgresql_public_ip" -p "$postgresql_port" -w template1 <<< "DROP DATABASE ${postgresql_database};"
+    PGPASSWORD="$admin_pw" PGUSER=root psql -h "$postgresql_public_ip" -p "$postgresql_port" -w template1 <<< "DROP USER ${APP};"
 
-    if [[ ! -f $app_path/ENV ]]; then
-      touch $app_path/ENV
-    fi
-
-    VARS=( "DATABASE_URL" )
-    clear_dokku_env VARS 
-
-    chown git: $app_path/ENV
+    dokku config:unset "$APP" DATABASE_URL
     ;;
   postgresql:list)
-    admin_pw=$(cat /home/git/.postgresql/admin_pw)
-    PGPASSWORD="$admin_pw" PGUSER=root psql -h localhost -p "$postgresql_port" -w template1 <<< "\list"
+    check_container
+
+    admin_pw=$(cat "$DOKKU_ROOT/.postgresql/admin_pw")
+    PGPASSWORD="$admin_pw" PGUSER=root psql -h "$postgresql_public_ip" -p "$postgresql_port" -w template1 <<< "\list"
+    ;;
+  postgresql:start)
+    if [[ "$id" != "" ]]; then
+      echo "Postgresql container already running with ID: ${id}"
+    else
+      docker run -p 5432:5432 -d -v "$DOKKU_ROOT/.postgresql/data":/var/lib/postgresql/9.1/main "$db_image" /usr/lib/postgresql/9.1/bin/postgres -D /var/lib/postgresql/9.1/main -c config_file=/etc/postgresql/9.1/main/postgresql.conf
+    fi
+    ;;
+  postgresql:stop)
+    check_container
+    mongo $postgresql_public_ip:$postgresql_port/admin --quiet -u admin -p"$admin_pass" --authenticationDatabase="admin" --eval "db.shutdownServer()"
+    ;;
+  postgresql:status)
+    if [[ "$id" != "" ]]; then
+      echo "Postgresql container running with ID: ${id}"
+    else
+      echo "Postgresql container not running"
+    fi
+    ;;
+  help)
+    cat && cat<<EOF
+    postgresql:create <app> Create a Mongo database
+    postgresql:delete <app> Delete specified Mongo database
+    postgresql:start        Start the Postgresql docker container if it isn't running
+    postgresql:stop         Stop the Postgresql docker container
+    postgresql:status       Shows status of Postgresql
+    postgresql:list         List all databases
+EOF
     ;;
 esac
 
